project:
  type: book
  output-dir: docs

book:
  title: "Advanced Computational Physics & Machine Learning"
  author: "Jim Brooke & Sudan Paramesvaran"
  #date: "15 Sept 2025"
  chapters:
    - index.qmd
    - intro.qmd
    - part: prog/programming.qmd
      chapters:
        - prog/basics.qmd
        - prog/oo.qmd
        - prog/functional.qmd
        - prog/exceptions.qmd
        - prog/parallel.qmd
        - prog/cloud.qmd
    - part: num/numeric.qmd
      chapters:
        - num/matrix.qmd
        - num/sim-eqn.qmd
        - num/eigenproblems.qmd
        - num/monte-carlo.qmd
        - num/optimisation.qmd
    - part: ml/ml.qmd
      chapters:
        - ml/intro-ml.qmd
        - ml/supervised-ml.qmd
        - ml/unsupervised-ml.qmd
        - ml/tl.qmd
        - ml/neural-networks.qmd
        - ml/cnn.qmd
        - ml/rnn.qmd
        - ml/transformer.qmd
        - ml/autoencoder.qmd
    - references.qmd

bibliography: references.bib
csl: american-physics-society-without-titles.csl

crossref:
  chapters: true 

format:
  html:
    theme: [cosmo, custom.scss]
  pdf:
    toc: true
    number-sections: true
    colorlinks: true




