project:
  type: book
  output-dir: docs

book:
  title: "Advanced Computational Physics & Machine Learning"
  author: "Jim Brooke & Sudan Paramesvaran"
  #date: "15 Sept 2025"
  chapters:
    - index.qmd
    - intro.qmd
    - part: programming.qmd
      chapters:
        - basics.qmd
        - oo.qmd
        - functional.qmd
        - exceptions.qmd
        - parallel.qmd
        - cloud.qmd
    - part: numeric.qmd
      chapters:
        - matrix.qmd
        - sim-eqn.qmd
        - eigenproblems.qmd
        - monte-carlo.qmd
        - optimisation.qmd
    - part: ml.qmd
      chapters:
        - intro-ml.qmd
        - supervised-ml.qmd
        - unsupervised-ml.qmd
        - tl.qmd
        - neural-networks.qmd
        - cnn.qmd
        - rnn.qmd
        - transformer.qmd
        - autoencoder.qmd
    - references.qmd

bibliography: references.bib
csl: american-physics-society-without-titles.csl

crossref:
  chapters: true 

format:
  html:
    theme: [cosmo, custom.scss]




