---
title: "Functional Programming"
format: html
execute:
  error: true
---


Functional programming is another programming paradigm.  In some respects it is quite the opposite of OO programming.  Objects intrinsically have some 'state' associated with them, due to their attributes (internal data).  So the result of a function call in OO programming (ie. a method) will depend on both the arguments passed to the function, and the state of the object upon which the method is called.

Conversely, in functional programming, computation is expressed in terms of functions which have no state. This paradigm is based on a formal system called λ-calculus, which has been shown to be Turing-complete, ie. it can simulate any Turing machine, or it can implement any computer algorithm. There are several languages (eg. Haskell, Erlang) which are designed to enforce functional programming.  It is possible to write fully functional programs in Python, using lambda functions.

Developing full functional programs is beyond the scope of this unit, but it should be noted that functional programming can be extremely useful in distributed computing. Because functions have no state, all the data they need to operate is passed as an argument.  This means it doesn't really matter _where_ the function runs.  Provided there is a network connection to the computer which is running the function, the arguments to the function call and the returned value can be communicated.  Conversely, in OO programming, methods need to be run in the same location as the obect attributes they are associated with.  This means OO programs can be harder to run in a distributed fashion than functional ones.

A full introduction to functional programming is beyond the scope of the unit, but below we introduce the syntax for lambda functions, and some particular cases where they can be useful.

## Lambda Functions

In Python, lambda functions are created using the lambda keyword, eg.: lambda: x, x**2 returns an “anonymous” function that takes one argument, and returns a value that depends only on the argument (in this case, the square). Compare this to regular functions, which are declared with def and are named
 :

```{python}
def function(x):
    return 0.5*x**2 + x + 1
function(4)
```

The equivalent using a lambda function would be :

```{python}
(lambda x: 0.5*x**2 + x + 1)(4)
```

## Anonymous functions
Lambdas can be useful when implementing mathematical expressions, and when working with functions that expect other functions as arguments. Eg. suppose I want to calculate $\int_1^4 e^{−x}$. I can
do this in one line with a lambda function :

```{python}
import scipy.integrate
import math

scipy.integrate.quad(lambda x: math.exp(-1*x), 1., 4.)
```

## Map-Reduce with Lists

Another area where lambda functions are useful is in the “map-reduce” paradigm. The idea here is that when processing large amounts of data, you want to do as much processing in parallel as possible. A given algorithm is divided into a parallel part (map), and a non-parallel part (reduce). When processing huge datasets, the map will be running in parallel on multiple machines. In Python, the map() function takes a function and a list as arguments. The function is applied to each element in the list, and then a list of the results is returned. Eg. to calculate the expression below for for n = 1000 :
$$
\sum_{i=1}^n i^2
$$

```{python}
import numpy as np
from functools import reduce

x = np.arange(0,1000)

squares = list(map((lambda x: x**2), x))
sum = reduce((lambda x, y: x+y), squares)

print(sum)
```

Another useful function when working with lists is filter(). This takes a function and a list, applies the function to each element, and retains that element if the function returns True. For example, you can try writing a function that accepts the odd values in a list of integers.